### ISSUE TITLE
Первое ревью

### ISSUE THREAD

**Issue by MarinaPaley** [FrozeRain/miit.study.cycled-linled-list#1]
1.  Придирки по коду. Не используйте +, используйте Join
1.  Осталось написать итератор

**Comment by FrozeRain** [comment]
Добрый день, @MarinaPaley .
Спасибо за Ваше ревью. Итератор объявлен в конце класса `com.miit.study.cyclelinkedlist.model.impl.CycleLinkedListImpl.CycleIterator`. В Main классе была произведена проверка итератора за счет вызова метода `com.miit.study.cyclelinkedlist.model.impl.CycleLinkedListImpl#iterator` у экземпляра коллекции.

**Comment by MarinaPaley** [comment]
Да, нашла, хорошо
